### ISSUE TITLE
如何用ai与QQ平台上的人对战

### ISSUE THREAD

**Issue by rccccat** [tangyan02/ego#1]
请问是怎样实现的 可以给出一些细节吗

**Comment by tangyan02** [comment]
其实做法比较原始，首先我写了一个网页版的界面，可以与AI对战。然后打开QQ平台，自己充当“机械臂”，在网页版中模拟QQ平台的对局 :-) 。记得要把时间设置短一点，不然让对手等待太久会体验不好，导致对手不愿意再和你下棋。我的程序一般设定为3到15秒左右出结果。

**Comment by rccccat** [comment]
thanks

**Comment by tangyan02** [comment]
全自动下棋工具已更新：）
https://github.com/tangyan02/GomokuQQPlayer
