### ISSUE TITLE
//判断是否随机开局 是什么意思

### ISSUE THREAD

**Issue by fucusy** [tangyan02/ego#2]
https://github.com/tangyan02/ego/blob/master/src/main/java/ego/gomoku/core/Game.java#L55

选随机开局，黑棋更容易输吗？不选随机开局，用最聪明的AI黑棋能不能必胜。

**Comment by tangyan02** [comment]
随机如果开启会从预先设计的开局方式中随机选一个
就目前随机的几个开局，理论上黑棋无禁都可以必胜。
不过目前这个ai不能保证必胜，不随机的情形ai会选择计算出来的优势更大的策略。

**Comment by tangyan02** [comment]
随机如果开启会从预先设计的开局方式中随机选一个
就目前随机的几个开局，理论上黑棋无禁都可以必胜。
不过目前这个ai不能保证必胜，不随机的情形ai会选择计算出来的优势更大的策略。
