### ISSUE TITLE
每次预测位置都要新建一个GomokuPlayer对象吗？

### ISSUE THREAD

**Issue by ChesterChai** [tangyan02/ego#4]
使用过程中发现每次预测位置都要新建一个GomokuPlayer对象。而且在棋子比较少的时候预测的也很慢。

**Comment by tangyan02** [comment]
需要新建一个对象，一次新建对象本身开销非常小。
一次落子时间取决于配置的参数，例如VERY_HIGH是最慢的一次落子在30s内，HIGH的一次落子时间在15s内。
c++移植版性能会更高，支持piskvork中运行。

**Comment by ChesterChai** [comment]
我最近在做手机端的五子棋游戏，打算使用它来作为AI引擎，实际使用中发现Level.EASY时间倒是可以忍受，但是一旦上升到了Level.NORMAL，等待的时间就有些长了。作为手机上运行的AI引擎是否有些偏“重”了。

**Comment by tangyan02** [comment]
在gomokuplayer中提供的level是为了预设的层数和超时时间两种参数。如果想减少等待，可以调整gomokuplayer构造函数中的超时时间。

**Comment by ChesterChai** [comment]
OK，了解了，谢谢解答。
